---
- name: stop the kubelet service
  service: 
    name: kubelet 
    state: stopped 
    enabled: no
  ignore_errors: true

- name: clear dce-bootstrap
  shell: docker rm -f dce-bootstrap > /dev/null 2>&1
  ignore_errors: true

- name: leave cluster
  shell: docker run --name dce-bootstrap --rm -t -v /var/run/docker.sock:/var/run/docker.sock -v /etc/daocloud:/etc/daocloud -v /var/local:/var/local --network host {{ DCE_HUB_PREFIX }}/dce:{{ dce_version }} do-uninstall --force --quiet
  register: result
  until: result.stdout.find('Uninstalled DCE') != -1
  retries: "{{ RETRIES }}"
  delay: "{{ DELAY }}"
