---
- include_tasks: timezone.yml
- include_tasks: selinux.yml
- include_tasks: firewalld.yml
- include_tasks: hostname.yml
- include_tasks: centos7_online_repo.yml
  when: not (DCE_OFFLINE_REPO != '' and DCE_HUB_PREFIX != 'daocloud.io')
- include_tasks: centos7_offline_repo.yml
  when: DCE_OFFLINE_REPO != '' and DCE_HUB_PREFIX != 'daocloud.io'

- name: yum.conf skip_broken=1
  ini_file:
    path: /etc/yum.conf
    section: main
    option: skip_broken
    value: 1

- name: install dce depends
  yum: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - wget
    - git
    - net-tools
    - bind-utils
    - iptables-services
    - bridge-utils
    - bash-completion
    - kexec-tools
    - sos
    - psacct
    - chrony
    - device-mapper-persistent-data
    - lvm2
    - audit
    - socat
    - ipvsadm

- name: configure chrony
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  notify: restart chrony

- name: start the chrony service
  service:
    name: chronyd
    state: started
    enabled: yes

- name: yum.conf obsoletes=0
  ini_file:
    path: /etc/yum.conf
    section: main
    option: obsoletes
    value: 0

- name: install kubelet-{{ kubelet_version }} & docker-ce-{{ docker_version }}
  yum: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - kubelet-{{ kubelet_version }}
    - docker-ce-{{ docker_version }}

- name: yum.conf obsoletes=1
  ini_file:
    path: /etc/yum.conf
    section: main
    option: obsoletes
    value: 1

- name: vg {{ VG_NAME }}
  lvg:
    vg: "{{ VG_NAME }}"
    pvs: "{{ THINPOOL_DISKS }}"
    pesize: "{{ VG_PE_SIZE }}"
    state: present
  ignore_errors: true
  tags: vg_create

- name: _VG_SIZE
  shell: vgs --noheadings --nosuffix --units s -o vg_size {{ VG_NAME }}
  register: res_VG_SIZE
  ignore_errors: true

- set_fact: 
    _META_SIZE={{ res_VG_SIZE.stdout / 1000 + 1 }}
  ignore_errors: true

- name: thinpool {{ THINPOOL_NAME }}
  lvol:
    vg: "{{ VG_NAME }}"
    lv: "{{ THINPOOL_NAME }}"
    size: 100%FREE
    opts: --type thin-pool --zero n --chunksize {{ THIN_POOL_CHUNK_SIZE }} --poolmetadatasize {{ _META_SIZE }}s
  ignore_errors: true
  tags: thinpool_create

- name: /dev/mapper/{{ VG_NAME }}-{{ THINPOOL_NAME }} exists ?
  stat: 
    path: /dev/mapper/{{ VG_NAME }}-{{ THINPOOL_NAME }}
  register: thinpool_exists

- name: create docker configuration directory(/etc/docker)
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0700

- name: docker_config_thinpool
  include_tasks: docker_config_thinpool.yml
  when: thinpool_exists.stat.exists

- name: docker_config_no_thinpool
  include_tasks: docker_config_no_thinpool.yml
  when: not thinpool_exists.stat.exists

- name: systemd daemon-reload
  systemd:
    daemon-reload: yes

- name: start docker
  service: 
    name: docker
    state: started 
    enabled: yes
