---
- name: yum repo
  include_tasks: centos7_online_repo.yml
  when: not offline | default(false)

- name: yum repo
  include_tasks: centos7_offline_repo.yml
  when: offline | default(false)

- name: yum.conf skip_broken=1
  ini_file:
    path: /etc/yum.conf
    section: main
    option: skip_broken
    value: 1

- name: install dce depends
  yum: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - wget
    - git
    - net-tools
    - bind-utils
    - iptables-services
    - bridge-utils
    - bash-completion
    - kexec-tools
    - sos
    - psacct
    - chrony
    - device-mapper-persistent-data
    - lvm2
    - audit
    - socat
    - ipvsadm

- name: configure chrony
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  notify: restart chrony

- name: start the chrony service
  service:
    name: chronyd
    state: started
    enabled: yes

- name: yum.conf obsoletes=0
  ini_file:
    path: /etc/yum.conf
    section: main
    option: obsoletes
    value: 0

- name: install kubelet-{{ kubelet_version }} & docker-ce-{{ docker_version }}
  yum: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - kubelet-{{ kubelet_version }}
    - docker-ce-{{ docker_version }}

- name: yum.conf obsoletes=1
  ini_file:
    path: /etc/yum.conf
    section: main
    option: obsoletes
    value: 1

- name: systemd daemon-reload
  systemd:
    daemon-reload: yes

- name: start docker
  service: 
    name: docker
    state: started 
    enabled: yes

- name: vg {{ vg_name }}
  lvg:
    vg: "{{ vg_name }}"
    pvs: "{{ thinpool_disks }}"
    pesize: "{{ vg_pe_size }}"
    state: present
  ignore_errors: true
  tags: vg_create

- name: thinpool {{ thinpool_name }}
  lvol:
    vg: "{{ vg_name }}"
    lv: "{{ thinpool_name }}"
    size: 100%FREE
    opts: --type thin-pool --chunksize {{ thin_pool_chunk_size }}
  ignore_errors: true
  tags: thinpool_create

- name: /dev/mapper/{{ vg_name }}-{{ thinpool_name }} exists ?
  shell: ls /dev/mapper/{{ vg_name }}-{{ thinpool_name }}
  register: thinpool_exists
  ignore_errors: true

- name: docker config
  include_tasks: docker_config_thinpool.yml
  when: thinpool_exists | succeeded

- name: docker config no thinpool
  include_tasks: docker_config_no_thinpool.yml
  when: thinpool_exists | failed

