- name: yum.conf skip_broken=1, obsoletes=0
  ini_file:
    path: /etc/yum.conf
    section: main
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: skip_broken, value: 1 }
    - { option: obsoletes, value: 0 }

- name: install dce depends
  yum: 
    name: "{{ item }}"
    state: present
    disablerepo: "*"
    enablerepo: dce_offline
    update_cache: yes
  with_items:
    - wget
    - git
    - net-tools
    - bind-utils
    - iptables-services
    - bridge-utils
    - bash-completion
    - kexec-tools
    - sos
    - psacct
    - chrony
    - device-mapper-persistent-data
    - lvm2
    - audit
    - socat
    - ipvsadm

- name: configure chrony
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  notify: restart chrony

- name: start the chrony service
  service:
    name: chronyd
    state: started
    enabled: yes
