---
- name: get all cluster nodes
  uri:
    url: http://{{ groups['seed'][0] }}/nodes
    method: GET
    return_content: yes
  register: WEBPAGE
  retries: "{{ retries | default(3) }}"
  delay: "{{ delay | default(10) }}"
  ignore_errors: true

- set_fact: 
    node_meta="{% for node in WEBPAGE.json %} 
                 {% if node.Status.Addr == inventory_hostname %}
                     {{ node.ID }},{{ node.Spec.Role }},{{ node.Version.Index }}
                 {% endif %}
               {% endfor %}"
- set_fact: 
    node_id="{{ node_meta.strip().split(',')[0] }}"
    node_role="{{ node_meta.strip().split(',')[1] }}"
    node_version="{{ node_meta.strip().split(',')[2] }}"

- name: demote {{ inventory_hostname }}
  uri:
    url: http://{{ groups['seed'][0] }}/nodes/{{ node_id }}/update?version={{ node_version }}
    method: POST
    body: {"Availability": "active", "Role": "worker"}
    body_format: json
    status_code: 200
    return_content: yes
  retries: "{{ retries | default(3) }}"
  delay: "{{ delay | default(10) }}"
  when: node_role == 'manager'

- name: clear dce-bootstrap
  shell: docker rm -f dce-bootstrap > /dev/null 2>&1
  ignore_errors: true

- name: dce uninstall
  shell: docker run --name dce-bootstrap --rm -t -v /var/run/docker.sock:/var/run/docker.sock -v /etc/daocloud:/etc/daocloud -v /var/local:/var/local --network host {{ dce_image }} do-uninstall --force --quiet
  register: result
  until: result.stdout.find('Uninstalled DCE') != -1
  retries: "{{ retries | default(3) }}"
  delay: "{{ delay | default(10) }}"

- name: rm {{ inventory_hostname }}
  uri:
    url: http://{{ groups['seed'][0] }}/nodes/{{ node_id }}
    method: DELETE
    status_code: 200
  register: res
  retries: "{{ retries | default(3) }}"
  delay: "{{ delay | default(10) }}"

- name: stop the kubelet service
  service: 
    name: kubelet 
    state: stopped 
    enabled: no
  ignore_errors: true

