---
- name: sync sync_image.sh
  template:
    src: sync_image.sh.j2
    dest: /tmp/sync_image.sh
    owner: root
    group: root
    mode: 0755

- name: pull dce {{ dce_version }}
  shell: bash /tmp/sync_image.sh

- name: clean dce_upgrade.sh
  file:
    path: /tmp/sync_image.sh
    state: absent
